server:
  port: 8081

spring:
  application:
    name: itemservice
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:items
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    hostname: localhost

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#    preferIpAddress: true