server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: itemservice
          uri: http://localhost:8081/
          predicates:
            - Path=/items/**
        - id: cartservice
          uri: http://localhost:8082/
          predicates:
            - Path=/cart/**
eureka:
  instance:
    hostname: localhost